# Generated by Django 4.2.11 on 2024-04-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('street_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('activity_type', models.CharField(choices=[('WALK', 'Walking'), ('RUN', 'Running'), ('JOG', 'Jogging'), ('CYCLE', 'Cycling'), ('SEDENTARY', 'Sedentary')])),
            ],
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('WALK', 'Walking'), ('RUN', 'Running'), ('JOG', 'Jogging'), ('CYCLE', 'Cycling'), ('SEDENTARY', 'Sedentary')])),
                ('days_duration', models.IntegerField()),
                ('note', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TMP', 'Temperature'), ('HUM', 'Humidity'), ('BPM', 'Beats Per Minute')], max_length=3)),
                ('value', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnp', models.CharField(blank=True, max_length=13, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('work_place', models.CharField(blank=True, max_length=100, null=True)),
                ('allergies', models.CharField(blank=True, max_length=200, null=True)),
                ('activity_type', models.CharField(blank=True, choices=[('WALK', 'Walking'), ('RUN', 'Running'), ('JOG', 'Jogging'), ('CYCLE', 'Cycling'), ('SEDENTARY', 'Sedentary')], null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('health_warnings', models.ManyToManyField(blank=True, null=True, to='api.healthwarning')),
                ('recommandations', models.ManyToManyField(blank=True, null=True, to='api.recommandation')),
                ('sensor_data', models.ManyToManyField(blank=True, null=True, to='api.sensordata')),
            ],
        ),
    ]
