# Generated by Django 4.2.11 on 2024-04-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address_healthwarning_recommandation_sensordata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pacient_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pacientprofile'),
        ),
    ]
